name: Run unit tests

on: push

jobs:
    run-tests:
        name: Setup & run tests
        runs-on: ubuntu-latest
        env:
            NODE_VERSION: 14.15.5

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  submodules: "recursive"

            - name: Setup Node.js ${{ env.NODE_VERSION }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Update NPM
              run: npm install -g npm

            - name: Install auto-changelog
              run: npm install -g auto-changelog

            - name: Install NPM dependencies
              run: npm install

            - name: Run tests with ts-jest
              run: npm test
